### PR TITLE
Fix the `cacheKey` type

### LINKED ISSUE #50: [TypeScript] cacheKey arguments array isn't automatically typed
In v5, the cacheKey arguments were automatically typed based on the method signature. In v6, the cacheKey arguments extend `unknown` instead of getting them from the original function.

Example error:

```ts
const example = mem(
  (str: string, strArray: string[]) => { /* do stuff */  },
  {
    // Typescript error on strArray: 
    // TS2461: Type 'unknown' is not an array type.
    cacheKey: ([str, strArray]) => [str, ...strArray].join()
    //                                   ^^^^^^^^^^^ <- Example error
  }
);
```

Workaround:

```ts
const example = mem(
  (str: string, strArray: string[]) => { /* do stuff */  },
  {
    // Repeat the types of the arguments inside of [ ].
    cacheKey: ([str, strArray]: [string, string[]]) => [str, ...strArray].join()
    //                        ^^^^^^^^^^^^^^^^^^^^ <- Example workaround
  }
);
```

I'm not sure if this can be fixed using generics, so it might just be some documentation for those confused when upgrading.

### PR DESCRIPTION
**Pull request by owenallenaz**
Fixes #50

### CODE REVIEW

**Comment by fregante** [comment]
This needs to be rebased on `master`:

```
git fetch origin master && git merge origin/master
// or
git fetch upstream master && git merge upstream/master
```

**Comment by owenallenaz** [comment]
Tests are fixed. In the test.ts there are a whole mess of @ts-expect-error, almost all of those are unnecessary if the initial fn is initialized with `..._arguments: any` this way you're telling TS that you're gonna call that FN with all kinds of parameter configurations, which is what most of these tests are doing. I made this change only in the two fns that are failing as a result of my changes.

**Review by fregante — APPROVED** [review]
🎉 

@sindresorhus you might want to release this as v8 because it’s probably still not compatible with the prematurely-published 7.0.0-2

**Comment by sindresorhus** [comment]
Thank you, @owenallenaz 🙌🏻

**Pull request merged**
