### PR TITLE
Add stats

### PR DESCRIPTION
**Pull request by Kikobeats**
I want to know your opinion about that.

I added a little stats objects useful under development to know if the memoized is working as you expected.

For avoid too much prints, I added the flag `maxStatsCalls` to setup the number of calls to print the debug message.

Also I added a name per each function to avoid be anonymous and be optimizable for v8.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why and for what do you need it? What problem does it solve? :)

**Comment by Kikobeats** [comment]
I'm using mem as cache level for avoid cpu cycles in a [string maching lexer/parser](https://github.com/Kikobeats/voll/blob/master/lib/evaluator.js#L3) and I needed to be sure that the rate of hits is good to add mem as dependency.

I choosed mem between other solutions because it haven't dependencies, just a smart wrapper around Map; I modified the core for control my case, but I thought in create this PR because I suppose that know cache stats is a generic and expected behavior that a memoized library could offer.

**Comment by SamVerschueren** [comment]
Actually you could create a more clever map instead and provide it as `cache` option.

```js
class IntelligentMap extends Map {

    constructor(iterable) {
        super(iterable);
        this.stats = {
            hit: 0,
            miss: 0
        }
    }

    get(key) {
        const ret = super.get(key);

        if (ret) {
            this.stats.hit++;
        } else {
            this.stats.miss++;
        }

        return ret;
    }
}
```

Use that as a map and you can achieve the same things as you want with this PR. And you can easily swap it out if you don't need it anymore.

**Comment by SamVerschueren** [comment]
I created something for you [stats-map](https://github.com/SamVerschueren/stats-map). Feel free to suggest extra features through PRs.

**Comment by Kikobeats** [comment]
I like that! more clean. but what is the point? use it at mem? close this PR? say to me guys 😄

**Comment by sindresorhus** [comment]
Good solution. @SamVerschueren Can you add a tip about `stats-map` to the readme?

**Comment by SamVerschueren** [comment]
You can use it with `mem` with the `cache` option.

```js
const mem = require('mem');
const StatsMap = require('stats-map');

const cache = new StatsMap();

const fnMem = mem(fn, {cache});

// Call fnMem()

console.log(cache.stats);
//=> {hits: 10, misses: 7}
```

> Can you add a tip about stats-map to the readme?

👍

**Comment by SamVerschueren** [comment]
Currently, `stats-map` in combination with `mem` will never increment the `misses`. The reason is because I do not extend the `has` method in `stats-map` and do not increment the stats when `has` is called but returns `false`.

I can override the `has` method like this

```js
has(key) {
    const ret = super.has(key);

    if (ret) {
        this.stats.hits++;
    } else {
        this.stats.misses++;
    }

    return ret;
}
```

But that means that in case of `mem`, if it has a `hit`, it will increment the hits by 2 because it will first call `has` (hits+1) and after that it will call `get` (hits+1).

Or should we only increment `misses` if ret is `false`?

```js
has(key) {
    const ret = super.has(key);

    if (!ret) {
        this.stats.misses++;
    }

    return ret;
}
```

**Comment by sindresorhus** [comment]
Hmm, we should actually only count hits in https://github.com/sindresorhus/mem/blob/65d4ab7fb3b43b71b3c968eff65329c8ebb3eee8/index.js#L21, which I don't see how would be possible using your Map subclass. Maybe it's would just be easier to add it here after all.

**Comment by SamVerschueren** [comment]
Actually, I could make that work. If I drop all the logic currently implemented and override the set method like this:

```js
set(key, value) {
    const data = value.data;

    Object.defineProperty(value, 'data', {
        get: () => {
            hits++;
            return data;
        }
    });

    super.set (key, value);
}

get(key) {
    misses++;
    return super.get (key)
}

has (key) {
    const has = super.has(key);

    if (!has) misses++;

    return has;
}
```

This should solve the mem use case. Happy to implement this is stats map.

On mobile, so might have some typos.

**Comment by sindresorhus** [comment]
:+1:

**Comment by SamVerschueren** [comment]
Just released `stats-map@1.0.0` which fixed all of this. I don't think someone will ever use it separately from `mem` because it's coupled to the implementation of `mem`. But I like that this issue got resolved quite elegantly :).

**Pull request closed without merging**
